version: "3"
services:

  hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 30000
      GRID_TIMEOUT: 30000

  chrome:
    image: selenium/node-chrome
    container_name: selenium-hub-chrome-node
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5555:5555"
    links:
      - hub
  
networks:
  default:
    external: true
    name: selenium-practice